name: Run Notebooks CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter pandas numpy matplotlib seaborn rich scipy
      - name: Prepare datasets
        run: |
          mkdir -p /scratch/rodrigo.freitas/remy-schedulers
          cp *.pkl /scratch/rodrigo.freitas/remy-schedulers/
      - name: Execute notebooks
        run: |
          jupyter nbconvert --to notebook --execute big_matrix.ipynb --ExecutePreprocessor.timeout=60 --ExecutePreprocessor.allow_errors=True --output big_matrix_out.ipynb
          jupyter nbconvert --to notebook --execute sim-compare.ipynb --ExecutePreprocessor.timeout=60 --ExecutePreprocessor.allow_errors=True --output sim-compare_out.ipynb
          jupyter nbconvert --to notebook --execute tb-compare.ipynb --ExecutePreprocessor.timeout=60 --ExecutePreprocessor.allow_errors=True --output tb-compare_out.ipynb

